# Configuração do Nixpacks para deploy no EasyPanel

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmd = "npx serve dist -s -p $PORT"

[variables]
NODE_ENV = "production"
VITE_NODE_ENV = "production"
